[package]
name = "lorgn_runtime"
description = "runtime for the LORGN language"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/MajorBarnulf/lorgn"

[dependencies]
lorgn_lang = "0.1"
gc = "0.4"
gc_derive = "0.4"
ron = "0.8"
