[package]
name = "lorgn_runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lorgn_lang = { path = "../lorgn_lang" }
gc = "0.4"
gc_derive = "0.4"
ron = "0.8"
